### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by gaetandezeiraud** [auth0-blog/electron-vue#2]
```
App threw an error during load
  Error: Module did not self-register.
      at process.func (electron/js2c/asar.js:138:31)
      at process.func [as dlopen] (electron/js2c/asar.js:138:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
      at Object.func (electron/js2c/asar.js:138:31)
      at Object.func [as .node] (electron/js2c/asar.js:138:31)
      at Module.load (internal/modules/cjs/loader.js:645:32)
      at Function.Module._load (internal/modules/cjs/loader.js:560:12)
      at Module.require (internal/modules/cjs/loader.js:685:19)
      at require (internal/modules/cjs/helpers.js:16:16)
      at Object.<anonymous> (C:\Users\gaeta\Documents\GitHub\electron-vue\node_modules\keytar\lib\keytar.js:1:14)
```

**Comment by fomin84** [comment]
i got same issue, how i can fix this?
